import PDFDocument from "pdfkit";
import type { InvoiceInputs } from "../src/types.js";
import { totalCents } from "./validation.js";

export async function invoicePdf(
  id: string,
  invoice: InvoiceInputs,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 56,
      info: {
        Title: `Northstar invoice ${id}`,
        Author: "Northstar Operations",
      },
    });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("error", reject);
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.fillColor("#17382d").fontSize(25).text("NORTHSTAR");
    doc
      .fillColor("#333333")
      .fontSize(11)
      .text("Operations / Synthetic demo invoice")
      .moveDown(3);
    doc.fontSize(28).text("Invoice").moveDown();
    doc
      .fontSize(11)
      .text(`Invoice: ${id}`)
      .text(`Bill to: ${invoice.customer}`)
      .text(`Terms: ${invoice.terms.replace("_", " ")}`)
      .moveDown(2);
    for (const item of invoice.items) {
      doc.fontSize(12).text(item.description);
      doc
        .fontSize(10)
        .text(
          `${item.quantity} × $${item.unitPrice.toFixed(2)} = $${(item.quantity * item.unitPrice).toFixed(2)}`,
        )
        .moveDown();
    }
    doc
      .moveDown()
      .fontSize(20)
      .text(`Total USD $${(totalCents(invoice.items) / 100).toFixed(2)}`);
    doc
      .moveDown(3)
      .fontSize(9)
      .fillColor("#777777")
      .text(
        "Generated by Once against the fictional Northstar application. No payment is due.",
      );
    doc.end();
  });
}
